# Enabled debugging commands
debugging: true

# url: the database connection URL (JDBC)
#     Supported URL:
#     <proto>:<engine>://<HOST>:<PORT>/?<params>
#     jdbc:mariadb://127.0.0.1:8000/
#     jdbc:mysql://github.tintinkung.com/
# name: The database name
# username: Database account name
# password: Database password
database:
  url: ""
  name: ""
  username: ""
  password: ""
  webhook-table: "plotsystem_discord_webhook"

# Channel ID references
# plot-notify: Notification channel to remind staffs the plots they haven't review
notification:
  channel-id: ""

# Forum channel tag
available-tag:
  on-going: "on-going"
  finished: "finished"
  rejected: "rejected"
  approved: "approved"
  archived: "archived"
  abandoned: "abandoned"

embed-color:
  on-going: "#808080" # Gray
  finished: "#fdcb58" # Yellow
  rejected: "#dd2e44" # Red
  approved: "#78b159" # Green
  archived: "#55acee" # Blue
  abandoned: "#aa8ed6" # Purple