# Enabled debugging commands
debugging: true

# url: the database connection URL (JDBC)
#     Supported URL:
#     <proto>:<engine>://<HOST>:<PORT>/?<params>
#     jdbc:mariadb://127.0.0.1:8000/
#     jdbc:mysql://asia.buildtheearth.asean/
# name: The database name
# username: Database account name
# password: Database password
database:
  url: ""
  name: ""
  username: ""
  password: ""
  webhook-table: "plotsystem_discord_webhook"

# Forum channel tag
available-tag:
  on-going: "on-going"
  finished: "finished"
  rejected: "rejected"
  approved: "approved"
  archived: "archived"
  abandoned: "abandoned"

embed-color:
  on-going: "#808080" # Gray
  finished: "#fdcb58" # Yellow
  rejected: "#dd2e44" # Red
  approved: "#78b159" # Green
  archived: "#55acee" # Blue
  abandoned: "#aa8ed6" # Purple

# Plot notification settings
# Disable what is not preferred
plot-notification:
  on-plot-submitted: false
  on-plot-reviewed: true
  on-plot-approved: true
  on-plot-rejected: true
  on-undo-review: true
  on-undo-submit: true
  on-plot-showcased: true

# ========================
# System Notification Settings
# ========================
system-notification:
  # ========================
  # Notification Channel
  # This must be set (as a valid channel ID) to enable the notification system.
  # ========================
  channel-id: ""

  # Optional message content to include in every notification embed.
  # Useful for tagging roles or users for important alerts (e.g., plot submissions).
  notification-content: ""

  # ========================
  # Notification Settings
  # Possible Values:
  # - DISABLED: Do not send notifications for this event.
  # - ENABLED: Send a notification with the default embed.
  # - WITH_CONTENT: Send a notification with extra content (if defined).
  # ========================

  # Notify un-categorized plugin related notifications
  notify-plugin-states: ENABLED

  # Whether to send system errors or exceptions as notifications.
  # Recommended for detecting issues such as failed plot tracking.
  notify-system-errors: ENABLED

  # ========================
  # Plot Management Commands
  # Defines which command, if it make changes to plot(s)
  # will trigger notifications.
  # ========================
  plot-commands:
    plot-archive: ENABLED
    plot-showcase: ENABLED
    plot-delete: ENABLED
    plot-fetch: ENABLED

  # ========================
  # Plot Status Notifications
  # Defines which plot status events will trigger notifications.
  # ========================
  plot-status:
    plot-created: ENABLED
    plot-submitted: WITH_CONTENT
    plot-approved: ENABLED
    plot-rejected: ENABLED
    plot-archived: ENABLED
    plot-inactive-abandoned: ENABLED
    plot-manually-abandoned: ENABLED