name: Report JUnit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  build:
    name: Report
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Local Maven Repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Run tests on all modules
        run: mvn test

      - name: Report Plugin Module
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:
          check_name: Plugin Module
          report_paths: 'discord-plotsystem/**/surefire-reports/TEST-*.xml'
          check_title_template: '<code>{{CLASS_NAME}}</code> › {{TEST_NAME}}'
          detailed_summary: true # display detailed summary of the report
          include_passed: true # include passed tests in the results table
          group_suite: true # Group tests by suite name
          comment: true # send comment in pull request

      - name: Report API Module
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:
          check_name: API Module
          report_paths: 'discord-plotsystem-api/**/surefire-reports/TEST-*.xml'
          check_title_template: '{{CLASS_NAME}} <sub><code><b>{{TEST_NAME}}</b></code></sub>'
          detailed_summary: true # display detailed summary of the report
          include_passed: true # include passed tests in the results table
          group_suite: false # Group tests by suite name
